#!/usr/bin/env ruby

ENV["HOME"] = "/Users/cho45"

require "pathname"
require "logger"

@log  = Logger.new(STDERR)
@log.level = Logger::DEBUG
@ssid = `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I`[/^\s*SSID: (.+)/, 1]

def sh(command)
	command = 'sudo -u cho45 ' + command
	@log.info command
	system(command)
end

def killall_ssh
	sh "killall ssh"
end

def set_screensaver_timeout(n)
	plist = Pathname.glob("#{ENV["HOME"]}/Library/Preferences/ByHost/com.apple.screensaver.*.plist")[0]
	hash  = plist.to_s[/\.([0-9A-F-]+)\.plist/, 1]
	name  = "ByHost/com.apple.screensaver.#{hash}"
	sh "defaults write #{name} idleTime -int #{n}"
end

## execution

killall_ssh

case @ssid
when "SNEG"
	set_screensaver_timeout(0)
else
	set_screensaver_timeout(180)
end

