#!/usr/bin/env ruby

require "pathname"

sty = ENV['STY']
pid = ARGV[0]
tty = `/bin/ps -o tty= -p #{pid}`.strip
win = Pathname.glob("/tmp/screen-#{sty}-*").find {|i| i.read[tty] }
if tty.empty? || !win
	exit 1
else
	puts win.to_s[/\d+$/]
	exit 0
end

